[2024-02-22T12:27:27.904+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-02-22T12:27:22.639839+00:00 [queued]>
[2024-02-22T12:27:27.917+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-02-22T12:27:22.639839+00:00 [queued]>
[2024-02-22T12:27:27.918+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-22T12:27:28.138+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-02-22 12:27:22.639839+00:00
[2024-02-22T12:27:28.148+0000] {standard_task_runner.py:60} INFO - Started process 53 to run task
[2024-02-22T12:27:28.154+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-02-22T12:27:22.639839+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpni5hh0x3']
[2024-02-22T12:27:28.157+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask reddit_extraction
[2024-02-22T12:27:28.305+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-02-22T12:27:22.639839+00:00 [running]> on host 3672373ca8db
[2024-02-22T12:27:28.444+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ACHRAF ZHAR' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-02-22T12:27:22.639839+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-22T12:27:22.639839+00:00'
[2024-02-22T12:27:30.007+0000] {logging_mixin.py:188} INFO - Connected to reddit !
[2024-02-22T12:27:31.952+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f15a64fc610>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/Palestine/top
[2024-02-22T12:27:33.466+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f15a64fca00>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/Palestine/top
[2024-02-22T12:27:40.138+0000] {python.py:201} INFO - Done. Returned value was: /opt/airflow/data/output/reddit_20240222_122727.csv
[2024-02-22T12:27:40.212+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20240222T122722, start_date=20240222T122727, end_date=20240222T122740
[2024-02-22T12:27:40.292+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-22T12:27:40.342+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
