[2024-02-20T16:01:18.194+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-02-20T16:01:15.184345+00:00 [queued]>
[2024-02-20T16:01:18.211+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-02-20T16:01:15.184345+00:00 [queued]>
[2024-02-20T16:01:18.212+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-20T16:01:18.239+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-02-20 16:01:15.184345+00:00
[2024-02-20T16:01:18.249+0000] {standard_task_runner.py:60} INFO - Started process 52 to run task
[2024-02-20T16:01:18.254+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-02-20T16:01:15.184345+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpxxw9j6cc']
[2024-02-20T16:01:18.257+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask reddit_extraction
[2024-02-20T16:01:18.334+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-02-20T16:01:15.184345+00:00 [running]> on host 484327e8d0c2
[2024-02-20T16:01:18.446+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ACHRAF ZHAR' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T16:01:15.184345+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-20T16:01:15.184345+00:00'
[2024-02-20T16:01:18.452+0000] {logging_mixin.py:188} INFO - Connected to reddit !
[2024-02-20T16:01:21.201+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 7, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etl.py", line 26, in extract_posts
    post = {key: post_dict[key] for key in POST_FIELDS}
  File "/opt/airflow/etls/reddit_etl.py", line 26, in <dictcomp>
    post = {key: post_dict[key] for key in POST_FIELDS}
KeyError: 'selftextscore'
[2024-02-20T16:01:21.221+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20240220T160115, start_date=20240220T160118, end_date=20240220T160121
[2024-02-20T16:01:21.278+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task reddit_extraction ('selftextscore'; 52)
[2024-02-20T16:01:21.304+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-20T16:01:21.335+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
